name: partpacker-server
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${PWD}/docker/caddy/config:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - partpacker
  partpacker:
    image: partpacker
    build:
      context: .
      dockerfile: docker/Dockerfile
      network: host
    ports:
      - "7860:7860"
    volumes:
      - ${PWD}/pretrained:/workspace/PartPacker/pretrained
      - ${PWD}/output:/workspace/PartPacker/output
    user: 0:0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - partpacker
    restart: unless-stopped

networks:
  partpacker:
    driver: bridge
volumes:
  caddy_data:
  caddy_config:
