services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "7860:7860"
    volumes:
      - ${PWD}/caddy/config:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ppTest

volumes:
  caddy_data:
  caddy_config:
networks:
  ppTest:
    external: true
